# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d07e6647ed90dafdda3deae9154df1de0efabfdd09b1c89306f3345db83f80b60419888f0bdbfa5a7b4940beb30bf77345ba1716e9465d32c754893ad8be8e3

test:
  secret_key_base: acd00e63cd469a92205fa11fc0482adb2e7592b800194c5149807decc7bf228863cc7203a3158dc81be4b3ce61b4745209eaf3e02d14918980a51908de90e79e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
